//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsAppointment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoctorsAppointmentDBEntities : DbContext
    {
        public DoctorsAppointmentDBEntities()
            : base("name=DoctorsAppointmentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Categories> Tbl_Categories { get; set; }
        public virtual DbSet<Tbl_Doctors> Tbl_Doctors { get; set; }
        public virtual DbSet<Tbl_Items> Tbl_Items { get; set; }
        public virtual DbSet<Tbl_Patients> Tbl_Patients { get; set; }
        public virtual DbSet<Tbl_Roles> Tbl_Roles { get; set; }
        public virtual DbSet<Tbl_Sheduling> Tbl_Sheduling { get; set; }
        public virtual DbSet<Tbl_users> Tbl_users { get; set; }
    }
}
