//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsAppointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Items()
        {
            this.Tbl_Doctors = new HashSet<Tbl_Doctors>();
            this.Tbl_Sheduling = new HashSet<Tbl_Sheduling>();
        }
    
        public long ID { get; set; }
        public string Item_Name { get; set; }
        public string Item_Desc { get; set; }
        public string Item_Image { get; set; }
        public string Location { get; set; }
        public Nullable<long> CategoriesID { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual Tbl_Categories Tbl_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Doctors> Tbl_Doctors { get; set; }
        public virtual Tbl_users Tbl_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sheduling> Tbl_Sheduling { get; set; }
    }
}
