//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsAppointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Patients()
        {
            this.Tbl_Sheduling = new HashSet<Tbl_Sheduling>();
        }
    
        public long ID { get; set; }
        public string PatientComment { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> DoctorID { get; set; }
    
        public virtual Tbl_Doctors Tbl_Doctors { get; set; }
        public virtual Tbl_users Tbl_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sheduling> Tbl_Sheduling { get; set; }
    }
}
