//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsAppointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Doctors()
        {
            this.Tbl_Patients = new HashSet<Tbl_Patients>();
            this.Tbl_Sheduling = new HashSet<Tbl_Sheduling>();
        }
    
        public long ID { get; set; }
        public string DoctorName { get; set; }
        public string DoctorImage { get; set; }
        public string DoctorDesc { get; set; }
        public string Specialist { get; set; }
        public Nullable<long> ItemID { get; set; }
    
        public virtual Tbl_Items Tbl_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Patients> Tbl_Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sheduling> Tbl_Sheduling { get; set; }
    }
}
