//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsAppointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sheduling
    {
        public long ID { get; set; }
        public string Sheduling_Date { get; set; }
        public string Sheduling_Time { get; set; }
        public string Sheduling_Period { get; set; }
        public Nullable<long> PatientID { get; set; }
        public Nullable<long> DoctorID { get; set; }
        public Nullable<long> ItemID { get; set; }
    
        public virtual Tbl_Doctors Tbl_Doctors { get; set; }
        public virtual Tbl_Items Tbl_Items { get; set; }
        public virtual Tbl_Patients Tbl_Patients { get; set; }
    }
}
